# Docker Compose for bitwarden

version: '2.1'
services:
  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    user: 1034:100 # docker_user:docker_group
    restart: unless-stopped
    dns: 192.168.1.20
    volumes:
      - /volume1/docker/bitwarden:/data
    ports:
      - 9090:1024
      - 3012:3012
    environment:
      ROCKET_PORT: '1024' # necessary for non-root running https://github.com/dani-garcia/bitwarden_rs/wiki/Running-docker-container-with-non-root-user
      WEBSOCKET_ENABLED: 'false' # Required to use websockets
      SIGNUPS_ALLOWED: 'false'   # set to false to disable signups