services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
      - N8N_HOST=n8n.homelab
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.homelab
      - GENERIC_TIMEZONE=Europe/Berlin
    volumes:
      - data:/home/node/.n8n

volumes:
  data:
    driver: local
      #driver_opts:
      #type: nfs
        #o: "nfsvers=4,addr=192.168.1.50,rw"
        #device: ":/volume1/docker/n8n/data"

