# Docker Compose for bitwarden

services:
  vaultwarden:
    image: vaultwarden/server:latest # 1.21.0:
    container_name: vaultwarden
    user: 1034:65538 # docker_user:docker_group
    restart: unless-stopped
    volumes:
      - nfs_vaultwarden_data:/data
    ports:
      - 1024:1024
      - 3012:3012
    environment:
      TZ: "Europe/Berlin"
      ROCKET_PORT: "1024" # necessary for non-root running https://github.com/dani-garcia/bitwarden_rs/wiki/Running-docker-container-with-non-root-user
      WEBSOCKET_ENABLED: "false" # Required to use websockets
      SIGNUPS_ALLOWED: "false"   # set to false to disable signups

volumes:
  nfs_vaultwarden_data:
    driver: local
    driver_opts:
      type: nfs
      o: "nfsvers=4,addr=192.168.1.50,rw"
      device: ":/volume1/docker/vaultwarden"
