# https://github.com/dani-garcia/vaultwarden/wiki/Using-Docker-Compose
services:
  vaultwarden:
    image: vaultwarden/server:latest # 1.21.0:
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - 1024:80
    environment:
      TZ: "Europe/Berlin"
      SIGNUPS_ALLOWED: "false"   # set to false to disable signups

volumes:
  data:
    driver: local
