version: "2.2"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
        - monitor_net
    ports:
        - 9090:9090
    command:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus
        - --storage.tsdb.retention.time=8d
    volumes:
        - /home/martin/dev/docker_archive/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        - nfs_volume_prometheus:/prometheus
    depends_on:
        - node_exporter
        - cadvisor
    restart: unless-stopped
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    networks:
        - monitor_net
    ports:
        - 9100:9100
    volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
    command:
        - --path.procfs=/host/proc
        - --path.rootfs=/rootfs
        - --path.sysfs=/host/sys
        - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)
    restart: unless-stopped
  cadvisor:
    image: budry/cadvisor-arm:latest
    # image: google/cadvisor:latest
    container_name: cadvisor
    networks:
        - monitor_net
    ports:
        - 8080:8080
    volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: 1000:1000
    networks:
        - monitor_net
    ports:
        - 3000:3000
    volumes:
        - nfs_volume_grafana:/var/lib/grafana
    depends_on:
        - prometheus


networks:
    monitor_net:
        driver: bridge

volumes:
    nfs_volume_prometheus:
        driver: local
        driver_opts:
            type: nfs
            o: "nfsvers=4,addr=192.168.1.50,rw"
            device: ":/volume1/docker/prometheus"
    nfs_volume_grafana:
        driver: local
        driver_opts:
            type: nfs
            o: "nfsvers=4,addr=192.168.1.50,rw"
            device: ":/volume1/docker/grafana"
