# Docker Compose for Watchtower

version: '2.1'
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    user: 1000:998 #martin:docker
    restart: unless-stopped
    dns: 192.168.1.20
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Berlin
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_DEBUG=true
      - NO_COLOR=false
      - WATCHTOWER_SCHEDULE=0 0 3 * * * # run once a day at 3 a.m.
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=telegram://${TOKEN}@telegram?channels=${USER_ID}
    command: watchtower portainer vaultwarden pihole heimdall librespeed home-assistant freshrss wireguard # update only listed containers
