services:
  evcc:
    command:
      - evcc
    container_name: evcc
    image: evcc/evcc:latest
    ports:
      - 7070:7070/tcp
      - 8887:8887/tcp
      - 7090:7090/udp
      - 9522:9522/udp
    volumes:
      - ./evcc.yaml:/etc/evcc.yaml
      - db:/root/.evcc
    restart: unless-stopped

volumes:
  db:
    driver: local
