version: "2.1"
services:
  librespeed:
    image: ghcr.io/linuxserver/librespeed:latest
    container_name: librespeed
    environment:
      - PUID=994
      - PGID=994
      - TZ=Europe/Berlin
    volumes:
      - /etc/docker/librespeed/config:/config
    ports:
      - 8181:80
    restart: unless-stopped