version: "2.1"
services:
  unifi-controller:
    image: ghcr.io/linuxserver/unifi-controller:latest
    container_name: unifi-controller
    dns: 192.168.1.20
    mac_address: 02:45:0b:00:02:09
    networks:
      pi-hole_macvlan_net:
        ipv4_address: 192.168.1.22
    environment:
      - PUID=1034
      - PGID=65538
      - MEM_LIMIT=1024M #optional
      - MEM_STARTUP=1024M #optional
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    volumes:
      - nfs_volume:/config
    restart: unless-stopped
volumes:
  nfs_volume:
    driver: local
    driver_opts:
      type: nfs
      o: "nfsvers=4,addr=192.168.1.50,rw"
      device: ":/volume1/docker/unifi-controller"
networks:
  pi-hole_macvlan_net:
    external: true
