# Docker Compose for Portainer

version: '2.1'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer_v2
    user: 1034:100 # docker_user:docker_group
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /volume1/docker/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
