services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - data:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

volumes:
  data:
    driver:
      local

