version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - nfs_homebridge_data:/homebridge
    environment:
      TZ: "Europe/Berlin"
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

volumes:
  nfs_homebridge_data:
    driver: local
    driver_opts:
      type: nfs
      o: "nfsvers=4,addr=192.168.1.50,rw"
      device: ":/volume1/docker/homebridge"
