version: "2.1"
services:
  freshrss:
    image: ghcr.io/linuxserver/freshrss:latest
    container_name: freshrss
    dns: 192.168.1.20
    environment:
      - PUID=996
      - PGID=996
      - TZ=Europe/Berlin
    volumes:
      - /etc/docker/freshrss:/config
    ports:
      - 808:80
    restart: unless-stopped
