# Docker Compose for bitwarden

services:
  revproxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: revproxy
    restart: unless-stopped
    volumes:
      - revproxy_data:/data
      - revproxy_letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 81:81
      - 443:443
    environment:
      - DB_SQLITE_FILE=/data/database.sqlite

volumes:
  revproxy_data:
    driver: local
  revproxy_letsencrypt:
    driver: local
