version: "2"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: 1034:100
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
      - "50000:50000"
    volumes:
      - /volume1/docker/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
