version: "2.1"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1034
      - PGID=65538
      - TZ=Europe/London
      - SERVERURL=${URL}
      - SERVERPORT=51820
      - PEERS=3
      - PEERDNS=192.168.1.20
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - nfs_volume:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
volumes:
  nfs_volume:
    driver: local
    driver_opts:
      type: nfs
      o: "nfsvers=4,addr=192.168.1.50,rw"
      device: ":/volume1/docker/wireguard-server"